### ISSUE TITLE
Donate functionality

### ISSUE THREAD

**Issue by M3kH** [HackYourFuture/hackyourfuture.github.io#40]
In the previous website we've the donation functionality.
This works with [ **Mollie**](https://www.mollie.com/en/).

Make sure that donation flow works again:
- Implement `/donate` in API
- Click in donate, shows overlay with asked amount
- Send the request to the donate endpoint
- Implement the [Mollie SDK](https://github.com/mollie/mollie-api-node) in the API endpoint

**Comment by isaachinman** [comment]
#43
